### ISSUE TITLE
autoinstallers

### ISSUE THREAD

**Issue by phoenixfire007** [RocketChat/rocketchat_nextcloud#13]
Well, with all the configuration issues I've sat with trying to get a self-hosted rocket.chat server running, I'd ask if there is an easier auto-installer. Because I've followed soooooo many help files and guide files, I'm still struggling to get rocketchat installed and working properly.

**Comment by pierrelocus** [comment]
Hi @phoenixfire007,

What OS are you using ?
You could try settings up your Rocket.Chat server with snap
Install snap if not already installed : https://snapcraft.io/docs/installing-snapd
Install RC with snap : https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/snaps

Keep me updated if it helps :)

**Comment by phoenixfire007** [comment]
I used ubuntu at the time. I've never used snap, and don't know it. I've tried various installations with docker. None have worked correctly. No matter how I configured it.

**Comment by small1** [comment]
The easy auto installers are snap or docker.  The manual guide för Debian or Ubuntu if done frrom scratch should work quickly as long as you get the right nodes and you do run each step

@phoenixfire007 Where do you get stuck on the way?

**Comment by ruvenss** [comment]
@phoenixfire007  Totally agree, it's tricky the ubuntu version can not be ANY version.

For bulletproof manual installation use Ubuntu 20.x
At least 2-4GB in ram and at least 2 vCPU
Follow these instructions step by step
[https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/debian-based-distros/ubuntu](https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/debian-based-distros/ubuntu)

Also I am going to close this issue since it doesn't belong here
